spring.application.name=tialudeliveryback

# Configuração básica do H2 (Banco de dados embutido)
spring.datasource.url=jdbc:h2:mem:tialudeliverydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permite que o H2 crie o esquema automaticamente
spring.jpa.hibernate.ddl-auto=update
