spring.application.name=tialudeliveryback

# CONFIGURAÇÃO DO BANCO DE DADOS H2 EM MEMÓRIA
spring.datasource.url=jdbc:h2:mem:tialudeliverydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permite ao Hibernate criar as tabelas (Entities) automaticamente
spring.jpa.hibernate.ddl-auto=create-drop

# Ativa o console web do H2 para você inspecionar os dados
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
